title: Michael Solomentsev's Website
description: Website & Blog
show_downloads: false
theme: minima

author:
  name: Michael Solomentsev
  email: "michael.solomentsev@gmail.com"

minima:
  skin: dark
  nav_pages:
    - blogIndex.md