title: Michael Solomentsev
#description: Website & Blog
show_downloads: false
blogurl:

plugins:
  - jekyll-remote-theme


remote_theme: "jekyll/minima"

author:
  name: Michael Solomentsev

minima:
  skin: dark
  header_pages:
  - index.html
  - blogIndex.md